defmodule Ueberauth.Strategy.Amco.API do
  alias OAuth2.Response
  alias Ueberauth.Strategy.Amco.OAuth

  @doc """
  Gets authorization's claims based on an access token. The claims will
  depend on the scope that was used in the authorization process.

  ## Parameters

    - access_token: String [Access token generated by the IdP].

  ## Examples

      iex> userinfo("bGWcAKadGrBwM...")
      {:ok, %{email: "test@example", phone_number: "+523344556677"}}

      iex> userinfo("InvalidAccessToken")
      {:error, :invalid}

  """
  def userinfo(access_token) do
    OAuth.userinfo(access_token)
    |> process_userinfo_response()
  end

  defp process_userinfo_response({:ok, %Response{status_code: 200, body: body}}) do
    {:ok, BetterParams.symbolize_merge(body, drop_string_keys: true)}
  end

  defp process_userinfo_response(_), do: {:error, :access_token_invalid}
end
